"""create metrics and anomalies hypertables

Revision ID: 304a8e9fe806
Revises: d880b35beeea
Create Date: 2026-06-24 10:23:20.693287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '304a8e9fe806'
down_revision: Union[str, Sequence[str], None] = 'd880b35beeea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomalies',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('mean', sa.Numeric(), nullable=False),
    sa.Column('std_dev', sa.Numeric(), nullable=False),
    sa.Column('z_score', sa.Numeric(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'detected_at', 'kind')
    )
    op.create_table('metrics',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_seconds', sa.BigInteger(), nullable=False),
    sa.Column('vwap', sa.Numeric(), nullable=True),
    sa.Column('volume', sa.Numeric(), nullable=False),
    sa.Column('volatility', sa.Numeric(), nullable=True),
    sa.Column('open_price', sa.Numeric(), nullable=True),
    sa.Column('high_price', sa.Numeric(), nullable=True),
    sa.Column('low_price', sa.Numeric(), nullable=True),
    sa.Column('close_price', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'computed_at', 'window_seconds')
    )
    op.execute("SELECT create_hypertable('metrics', by_range('computed_at'));")
    op.execute("SELECT create_hypertable('anomalies', by_range('detected_at'));")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metrics')
    op.drop_table('anomalies')
    # ### end Alembic commands ###
