"""create trades hypertable

Revision ID: d880b35beeea
Revises:
Create Date: 2026-06-18 10:07:40.549886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd880b35beeea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trades',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('is_buyer_maker', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'id', 'timestamp')
    )
    op.create_index('ix_trades_symbol_timestamp', 'trades', ['symbol', 'timestamp'], unique=False)
    op.execute("SELECT create_hypertable('trades', by_range('timestamp'));")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trades_symbol_timestamp', table_name='trades')
    op.drop_table('trades')
    # ### end Alembic commands ###
